#!/usr/bin/env python3
"""
ECS programmatic local-SEO matrix builder.

Renders {service} x {city} pages from scripts/matrix_data.py, keeps sitemap.xml
in sync, and injects the crawl path (a "More in {City}" block) into the existing
real-estate-photography-{city}.html pages.

    python3 scripts/build_matrix.py            # build everything
    python3 scripts/build_matrix.py --dry-run  # report, write nothing
    python3 scripts/build_matrix.py --check    # verify built pages match data (CI-ish)

Design notes
------------
* The visual shell (inline <style>, header, footer, motion scripts) is lifted
  verbatim from an existing city page, so matrix pages inherit Edition 03 brand
  styling with no separate CSS to drift.
* Every generated file carries a GENERATED marker. The builder refuses to
  overwrite a file that does not carry it, so a hand-edited page is never
  silently clobbered.
* Idempotent: running twice produces byte-identical output.
"""

import argparse
import html
import json
import os
import re
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from matrix_data import CITIES, SERVICES, SERVICE_ORDER, CITY_ORDER, PRICING, PHONE, PHONE_TEL  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DONOR = os.path.join(ROOT, "real-estate-photography-walker.html")
BASE = "https://elzingacreativestudio.com/"
GENERATED = "<!-- GENERATED by scripts/build_matrix.py — edit scripts/matrix_data.py, not this file -->"
CROSSLINK_START = "<!-- MATRIX-LINKS:START -->"
CROSSLINK_END = "<!-- MATRIX-LINKS:END -->"


# ------------------------------------------------------------------ shell bits

def load_shell():
    src = open(DONOR, encoding="utf-8").read()
    grab = lambda pat: re.search(pat, src, re.S).group(0)
    return {
        "gtm_head": grab(r"<!-- Google Tag Manager -->.*?<!-- End Google Tag Manager -->"),
        "gtm_body": grab(r"<!-- Google Tag Manager \(noscript\) -->.*?<!-- End Google Tag Manager \(noscript\) -->"),
        "fonts": grab(r'<link rel="preconnect".*?rel="stylesheet">'),
        "css": grab(r'<link rel="stylesheet" href="css/cobalt-gallery.css">\s*<link rel="stylesheet" href="css/brand.css">'),
        "style": grab(r"<style>.*?</style>"),
        "header": grab(r"<header id=\"site-header\">.*?</header>"),
        "footer_scripts": grab(r"<script>\s*const hdr = document\.getElementById.*?</body>\s*</html>"),
    }


def footer(city):
    return f"""<footer>
  <div><span class="footer-ecs">ECS</span><br><span class="footer-tag">Photography &middot; Video &middot; Marketing</span></div>
  <a href="index.html" style="font-size:10px;font-weight:800;letter-spacing:2px;text-transform:uppercase;color:rgba(255,255,255,0.6);text-decoration:none;">&larr; Back to Main Site</a>
  <div style="display:flex;flex-wrap:wrap;gap:8px;align-items:center;font-size:10px;letter-spacing:1.5px;color:rgba(255,255,255,0.25);">
    <span>PARTNERS</span>
    <a href="https://elevationhome.co" target="_blank" rel="noopener" title="Elevation Home Co" style="color:rgba(255,255,255,0.6);text-decoration:none;border:1px solid rgba(255,255,255,0.12);padding:3px 6px;font-weight:800;">Elevation Home Co.</a>
    <a href="https://elevationdoorco.com" target="_blank" rel="noopener" title="Elevation Door Co" style="color:rgba(255,255,255,0.6);text-decoration:none;border:1px solid rgba(255,255,255,0.12);padding:3px 6px;font-weight:800;">Elevation Garage Door</a>
    <a href="https://elevationexteriorcleaning.com" target="_blank" rel="noopener" title="Elevation Exterior Cleaning" style="color:rgba(255,255,255,0.6);text-decoration:none;border:1px solid rgba(255,255,255,0.12);padding:3px 6px;font-weight:800;">Elevation Exterior Cleaning</a>
  </div>
  <p class="footer-copy">&copy; {date.today().year} Elzinga Creative Studio. Grand Rapids, Michigan.<br>Serving {city['name']} from Grand Rapids. <a href="https://maps.app.goo.gl/eRag7okCqEp4HJdW9" rel="noopener" style="color:rgba(255,255,255,0.6);">See our Google reviews</a>.</p>
</footer>"""


# ------------------------------------------------------------------- utilities

def url_for(service_key, city_slug):
    return f"{SERVICES[service_key]['slug']}-{city_slug}.html"


def esc(s):
    """Escape for a JSON-LD string literal."""
    return json.dumps(s)[1:-1]


def bullets(items):
    return "\n".join(f"    <li>{i}</li>" for i in items)


# Varied tails so the drone bullet list never reads as one sentence stamped five times.
DRONE_BULLET_TAILS = [
    " &mdash; a high frame that reads as a lot map, so the parcel and the setting arrive together",
    " &mdash; mid-altitude context showing how the home sits against what is around it",
    " &mdash; a low approach that keeps the architecture the subject rather than the roof",
]


def gallery(city):
    figs = []
    alts = [
        "HDR interior of a West Michigan listing photographed by Elzinga Creative Studio",
        "Wide-angle HDR living space in a West Michigan listing photographed by Elzinga Creative Studio",
        "HDR dining and detail frame from a West Michigan listing photographed by Elzinga Creative Studio",
        "Exterior of a West Michigan listing photographed by Elzinga Creative Studio",
    ]
    for i, stem in enumerate(city["imgs"][:4]):
        figs.append(
            f'    <picture><source srcset="images/web/{stem}-1600.avif" type="image/avif">'
            f'<img src="images/web/{stem}-1600.jpg" alt="{alts[i % len(alts)]}" '
            f'width="1200" height="800" loading="lazy"></picture>'
        )
    return "\n".join(figs)


def nearby_block(service_key, city_slug, city):
    """Same service, nearby towns — plus the sibling services in this town."""
    svc = SERVICES[service_key]
    rows = []
    for n in city["nearby"]:
        if n in CITIES:
            rows.append(f'    <li><a href="{url_for(service_key, n)}"><strong>{CITIES[n]["name"]}, MI</strong>, {svc["short"]} for {CITIES[n]["name"]} listings</a></li>')
        else:
            # Town has a photography page but is outside the matrix — link that instead.
            pretty = n.replace("-", " ").title()
            rows.append(f'    <li><a href="real-estate-photography-{n}.html"><strong>{pretty}, MI</strong>, real estate photography</a></li>')
    siblings = [k for k in SERVICE_ORDER if k != service_key]
    sib_rows = [
        f'    <li><a href="{url_for(k, city_slug)}"><strong>{SERVICES[k]["nav_label"]} in {city["name"]}</strong>, {SERVICES[k]["price_line"]}</a></li>'
        for k in siblings
    ]
    sib_rows.append(f'    <li><a href="real-estate-photography-{city_slug}.html"><strong>Real estate photography in {city["name"]}</strong>, the full HDR listing gallery</a></li>')
    return f"""<section class="nearby-areas reveal">
  <div class="nearby-inner">
    <span class="nearby-label">Everything else in {city['name']}</span>
    <h2 class="nearby-title">More listing coverage in <em>{city['name']}.</em></h2>
    <ul class="nearby-list">
{chr(10).join(sib_rows)}
    </ul>
    <span class="nearby-label" style="margin-top:32px;display:block;">Nearby towns</span>
    <h2 class="nearby-title">{svc['label']} in nearby <em>West Michigan towns.</em></h2>
    <ul class="nearby-list">
{chr(10).join(rows)}
    </ul>
  </div>
</section>"""


def booking_block(city, extra=""):
    return f"""  <h2>How to book in {city['name']}</h2>
  <ul>
    <li><strong>For agents listing in {city['name']} regularly:</strong> join the <a href="preferred-photographer.html">Preferred Photographer Program</a> &mdash; standing 3-tier pricing, priority calendar, and a ${PRICING['referral_credit']} referral credit.</li>
    <li><strong>For a one-off listing:</strong> book on the <a href="real-estate-photography-{city['slug']}.html">{city['name']} real estate photography page</a>.</li>
    <li><strong>For a free critique first:</strong> submit a <a href="free-audit.html">free listing photo audit</a> and get a video back within 48 hours.</li>
  </ul>
  <p>{extra}Or <a href="sms:{PHONE_TEL}">text Kaden directly at {PHONE}</a>.</p>"""


def pricing_strip(title, note):
    return f"""  <div class="pricing-strip">
    <h3>{title}</h3>
    <div class="tiers">
      <div class="tier"><span class="tier-name">Essential</span><span class="tier-price">${PRICING['essential']}</span></div>
      <div class="tier"><span class="tier-name">Showcase</span><span class="tier-price">${PRICING['showcase']}</span></div>
      <div class="tier"><span class="tier-name">Signature</span><span class="tier-price">${PRICING['signature']}</span></div>
    </div>
    <p style="margin-top: 16px; margin-bottom: 0; font-size: 14px;">{note} <a href="preferred-photographer.html">See the full breakdown</a>.</p>
  </div>"""


def faq_html(pairs):
    return "\n".join(f"  <p><strong>{q}</strong><br>{a}</p>" for q, a in pairs)


def laanc_phrase(city):
    return {
        "required": "authorization is required for most addresses here",
        "partial": "authorization is required on part of the map here",
        "rare": "most addresses here need no authorization at all",
    }[city["airspace"]["laanc"]]


# ------------------------------------------------------------- page composers

def page_drone(city):
    n, s = city["name"], city["slug"]
    air = city["airspace"]
    body = f"""  <h2>What an aerial actually proves in {n}</h2>
  <p>{city['positioning']} <strong>{n} listings sell on {city['sells_on']}.</strong></p>
  <p>An aerial frame is the only one that shows {city['aerial']}. That is the whole argument for drone here: it is not a prettier photo, it is a different piece of information. A buyer scrolling a gallery on their phone can read a lot line, a tree canopy, or a five-minute commute in one frame, and cannot read any of it from a front elevation.</p>

  <h2>{n} airspace: what actually applies</h2>
  <p>{air['text']}</p>
  <p>Practically, that means {laanc_phrase(city)}. Every ECS flight is flown by a Part 107 certified Remote Pilot in Command, the airspace is checked against the FAA UAS facility map for your specific address before the shoot, and authorization is filed in advance where the grid calls for it. The flight is planned before the shoot day, not improvised in the driveway. For the full rundown see <a href="blog/drone-laws-grand-rapids-real-estate-agents.html">drone laws for Grand Rapids real estate agents</a>.</p>

  <h2>What we fly in {n}</h2>
  <ul>
{bullets(f"<strong>{b[0].upper() + b[1:]}</strong>{DRONE_BULLET_TAILS[i] if i < len(DRONE_BULLET_TAILS) else ''}" for i, b in enumerate(city['neighborhoods']))}
  </ul>

{pricing_strip(f"Drone pricing for {n} listings", f"Drone aerials are a ${PRICING['drone_addon']} add-on to Essential or Showcase and are included in the Signature tier. Every flight is Part 107 compliant, with LAANC filed ahead of time where {n} airspace requires it.")}

  <h2>How the flight is run</h2>
  <p>The aerial is captured during the same visit as the HDR stills, so there is no second appointment and no second invoice. Standard coverage is a set of context frames at varying altitude and angle: a high overhead that reads as a lot map, a mid-altitude three-quarter that shows the home in the neighborhood, and a low approach that keeps the architecture the subject. Weather calls are made the morning of, and a scrubbed flight moves rather than becoming a rushed one in bad light.</p>
  <p>Delivery is the same as the rest of the shoot: edited and back to you the next business day, sized for MLS and for social.</p>

{booking_block(city, f"{n} is {city['travel_note']}. ")}

  <h2>{n} drone photography FAQ</h2>
{faq_html([
    (f"Do you need LAANC authorization to fly a drone in {n}?", f"{air['text']} We handle the filing before the shoot, so the answer for an agent is simply yes, it is covered."),
    (f"How much does drone photography cost for a {n} listing?", f"${PRICING['drone_addon']} added to an Essential (${PRICING['essential']}) or Showcase (${PRICING['showcase']}) package, and included at no extra cost in Signature (${PRICING['signature']})."),
    (f"Is the drone pilot licensed?", "Yes. Every flight is flown by an FAA Part 107 certified Remote Pilot in Command. Commercial real estate drone work without Part 107 is not legal, and it is a fair question to ask any photographer before you hire them."),
    (f"How fast do I get the aerials back?", f"Next business day, the same as the rest of the shoot. Aerials for {n} listings are delivered edited and MLS-ready alongside the interiors and exteriors."),
])}"""
    return {
        "title": f"Drone Real Estate Photography {n}, MI | Elzinga Creative Studio",
        "desc": f"Part 107 drone and aerial photography for {n}, MI listings. LAANC handled, next-business-day delivery. ${PRICING['drone_addon']} add-on, included in Signature."[:158],
        "eyebrow": f"{city['eyebrow']} &middot; Drone &amp; Aerial",
        "h1": f"Drone real estate photography in <em>{n}</em>.",
        "sub": f"Part 107 aerials for {n} listings, with {air['class']} airspace handled before the shoot. ${PRICING['drone_addon']} on Essential or Showcase, included in Signature. Delivered next business day.",
        "body": body,
        "gallery_label": f"Aerial Work, {n}",
        "gallery_title": f"Aerials that show what the ground shot cannot.",
        "gallery_sub": f"Drone frames for {n} listings are shot to answer the question the gallery leaves open: how the property actually sits, how much land comes with it, and what is within a few minutes of the front door.",
        "cta": f"Listing in {n}? Let's get it in the air.",
        "faqs": [
            (f"Do you need LAANC authorization to fly a drone in {n}?", air["text"]),
            (f"How much does drone photography cost for a {n} listing?", f"${PRICING['drone_addon']} added to an Essential (${PRICING['essential']}) or Showcase (${PRICING['showcase']}) package, and included at no extra cost in the Signature tier (${PRICING['signature']})."),
            ("Is the drone pilot licensed?", "Yes. Every flight is flown by an FAA Part 107 certified Remote Pilot in Command."),
            (f"How fast do I get the {n} aerials back?", "Next business day, delivered edited and MLS-ready alongside the interiors and exteriors."),
        ],
    }


def page_video(city):
    n = city["name"]
    body = f"""  <h2>What video does in {n} that stills cannot</h2>
  <p>{city['positioning']}</p>
  <p>For this market the case for video is {city['reel']}. A still gallery is a set of disconnected rooms; a walkthrough is the only format that carries how a home actually connects, and a vertical cut is the only one that survives a thumb moving at speed.</p>

  <h2>What a {n} listing reel looks like</h2>
  <p>The standard deliverable is a vertical 9:16 cut for Instagram, Facebook, and TikTok: hooked in the first second, paced fast, captioned so it reads with the sound off, and ending on the address and your name rather than ours. It is shot during the same visit as the photos, so the listing gets stills and video from one appointment.</p>
  <ul>
{bullets([
    "<strong>The hook</strong> &mdash; the single best frame in the house, first, before anyone decides to scroll",
    "<strong>The walk</strong> &mdash; entry through the main living spaces in one continuous read, so the floor plan makes sense",
    "<strong>The proof</strong> &mdash; the two or three features this listing is actually priced on",
    f"<strong>The setting</strong> &mdash; a {n} exterior and, where it earns its place, a drone establishing shot",
    "<strong>The close</strong> &mdash; address, price point, and the agent's name and contact",
])}
  </ul>

  <div class="pricing-strip">
    <h3>Video pricing for {n} listings</h3>
    <div class="tiers">
      <div class="tier"><span class="tier-name">Agent Reel</span><span class="tier-price">${PRICING['reel_single']}</span></div>
      <div class="tier"><span class="tier-name">Reel Package</span><span class="tier-price">${PRICING['reel_package']}</span></div>
      <div class="tier"><span class="tier-name">Signature</span><span class="tier-price">${PRICING['signature']}</span></div>
    </div>
    <p style="margin-top: 16px; margin-bottom: 0; font-size: 14px;">A single-listing vertical reel is ${PRICING['reel_single']}. A multi-listing or branded package is ${PRICING['reel_package']}, useful for agents posting on a consistent cadence. Video attaches to any photo tier, and a drone establishing shot adds ${PRICING['drone_addon']}. <a href="real-estate-video-walkthrough-grand-rapids.html">See the full video breakdown</a>.</p>
  </div>

  <h2>Where the reel actually goes</h2>
  <p>The cut is delivered in a format you can post directly: vertical for Reels, Stories, and TikTok, with a horizontal export on request for a listing page or a YouTube upload. Most agents get more mileage out of the vertical, because it is the version that runs in the feed where buyers are already scrolling. The reel is yours, unbranded to ECS, so it works as your marketing rather than ours.</p>

  <h2>What we shoot in {n}</h2>
  <ul>
{bullets([f"<strong>{b[0].upper() + b[1:]}</strong>" for b in city['neighborhoods']])}
  </ul>

{booking_block(city, f"{n} is {city['travel_note']}. ")}

  <h2>{n} real estate video FAQ</h2>
{faq_html([
    (f"What does real estate video cost in {n}?", f"A single-listing vertical reel is ${PRICING['reel_single']}. A multi-listing or branded package is ${PRICING['reel_package']}. Video runs on top of any photo tier &mdash; Essential ${PRICING['essential']}, Showcase ${PRICING['showcase']}, or Signature ${PRICING['signature']}."),
    ("Do you shoot the video on the same visit as the photos?", "Yes. Stills and video are captured in the same appointment, which is why a listing can get both without a second scheduling round or a second trip charge."),
    ("Is the reel branded to you?", "No. The cut ends on your name and contact, not ours. It is your listing marketing."),
    (f"How fast do I get a {n} listing video back?", "Video is delivered on the same next-business-day standard as the photos in the great majority of cases; a longer multi-listing package is scheduled with a delivery date up front."),
])}"""
    return {
        "title": f"Real Estate Video {n}, MI | Listing Reels | Elzinga Creative Studio",
        "desc": f"Real estate video and vertical listing reels for {n}, MI agents. ${PRICING['reel_single']} single listing, ${PRICING['reel_package']} package. Shot with your photos, back next business day."[:158],
        "eyebrow": f"{city['eyebrow']} &middot; Listing Video",
        "h1": f"Real estate video for <em>{n}</em> listings.",
        "sub": f"Vertical listing reels for {n} agents, shot during the same visit as your photos. ${PRICING['reel_single']} for a single listing, ${PRICING['reel_package']} for a multi-listing or branded package. Delivered ready to post.",
        "body": body,
        "gallery_label": f"Recent Work, {n}",
        "gallery_title": "The stills the video is cut from.",
        "gallery_sub": f"Every {n} listing reel is built on the same shoot as the photo gallery, which is why the video and the stills look like the same house on the same day rather than two different marketing pieces.",
        "cta": f"Listing in {n}? Let's put it in motion.",
        "faqs": [
            (f"What does real estate video cost in {n}?", f"A single-listing vertical reel is ${PRICING['reel_single']} and a multi-listing or branded package is ${PRICING['reel_package']}, on top of any photo tier."),
            ("Do you shoot the video on the same visit as the photos?", "Yes. Stills and video are captured in the same appointment."),
            ("Is the listing reel branded to the photographer?", "No. The cut ends on the agent's name and contact."),
            (f"How fast is a {n} listing video delivered?", "Next business day in the great majority of cases, the same standard as the photos."),
        ],
    }


def page_tour(city):
    n = city["name"]
    body = f"""  <h2>Who the walkthrough is really for in {n}</h2>
  <p>{city['positioning']}</p>
  <p>The 3D tour earns its ${PRICING['tour_addon']} here on one specific buyer: {city['tour']}. A walkthrough link does a job no gallery can &mdash; it lets someone move through the floor plan on their own time, in their own order, and arrive at a showing already knowing whether the layout works.</p>

  <h2>What you actually get</h2>
  <ul>
{bullets([
    "<strong>An interactive walkthrough</strong> &mdash; a Zillow 3D Home and Matterport-style tour a buyer can navigate room to room from any device",
    "<strong>One link</strong> &mdash; drop it in the MLS, your listing page, an email, or a social post",
    "<strong>Captured on the same shoot</strong> &mdash; no second appointment, no second trip, no separate scheduling",
    f"<strong>A 2D floor plan option</strong> &mdash; add measurements for ${PRICING['floorplan']} so photos, dimensions, and the walkthrough all live in one place",
    f"<strong>A premium path</strong> &mdash; a fully hosted Matterport Pro tour runs ${PRICING['matterport_pro_low']} to ${PRICING['matterport_pro_high']}, custom-quoted, for higher-end listings that warrant it",
])}
  </ul>

{pricing_strip(f"3D tour pricing for {n} listings", f"The 3D tour is a ${PRICING['tour_addon']} add-on to any photo package, captured during the same session as your HDR stills. Photos plus a full interactive walkthrough lands between ${PRICING['essential'] + PRICING['tour_addon']} and ${PRICING['signature'] + PRICING['tour_addon']} depending on tier, and the Signature tier already includes a 3D walkthrough.")}

  <h2>Which {n} listings get the most out of it</h2>
  <ul>
{bullets([f"<strong>{b[0].upper() + b[1:]}</strong>" for b in city['neighborhoods']])}
  </ul>

  <h2>How it is captured</h2>
  <p>The scan runs alongside the photo shoot rather than as a separate visit, which adds time on site but not a second appointment on your calendar. The home should be shot-ready the same way it would be for stills: lights on, blinds set, counters clear, nothing in the frame that should not be there. Pets and people stay out of the scan for obvious reasons.</p>
  <p>The finished tour is delivered as a link on the same next-business-day standard as the photos.</p>

{booking_block(city, f"{n} is {city['travel_note']}. ")}

  <h2>{n} 3D tour FAQ</h2>
{faq_html([
    (f"How much does a 3D virtual tour cost in {n}?", f"It is a ${PRICING['tour_addon']} add-on to any photo package: Essential ${PRICING['essential']}, Showcase ${PRICING['showcase']}, or Signature ${PRICING['signature']} (which already includes a walkthrough). A fully hosted Matterport Pro tour is ${PRICING['matterport_pro_low']} to ${PRICING['matterport_pro_high']}, custom-quoted."),
    ("Is it a real Matterport tour?", f"The ${PRICING['tour_addon']} add-on covers Zillow 3D Home and a Matterport-style walkthrough, which is what the large majority of listings need. A premium, fully hosted Matterport Pro tour is available as a custom quote for higher-end properties."),
    ("Do you need a separate appointment for the tour?", "No. The scan is captured during the same session as the HDR stills, which is why it is priced as an add-on rather than as a standalone product."),
    (f"Can I add a floor plan to a {n} listing too?", f"Yes. A 2D floor plan is ${PRICING['floorplan']}, so a buyer gets photos, measurements, and a walkthrough from one shoot."),
])}"""
    return {
        "title": f"3D Virtual Tours {n}, MI | Matterport-Style Walkthroughs | ECS",
        "desc": f"3D virtual tours and Matterport-style walkthroughs for {n}, MI listings. ${PRICING['tour_addon']} add-on to any photo package, captured on the same shoot."[:158],
        "eyebrow": f"{city['eyebrow']} &middot; 3D Virtual Tour",
        "h1": f"3D virtual tours for <em>{n}</em> listings.",
        "sub": f"Zillow 3D Home and Matterport-style walkthroughs for {n} listings. A ${PRICING['tour_addon']} add-on to any photo package, captured during the same shoot and delivered as one link.",
        "body": body,
        "gallery_label": f"Recent Work, {n}",
        "gallery_title": "The stills that run alongside the walkthrough.",
        "gallery_sub": f"A 3D tour answers the layout question; the photo gallery is still what makes someone click. {n} listings get both from a single visit, which is the whole point of pricing the tour as an add-on.",
        "cta": f"Listing in {n}? Add the walkthrough.",
        "faqs": [
            (f"How much does a 3D virtual tour cost in {n}?", f"It is a ${PRICING['tour_addon']} add-on to any photo package: Essential ${PRICING['essential']}, Showcase ${PRICING['showcase']}, or Signature ${PRICING['signature']}."),
            ("Is it a real Matterport tour?", f"The ${PRICING['tour_addon']} add-on covers Zillow 3D Home and a Matterport-style walkthrough. A fully hosted Matterport Pro tour is ${PRICING['matterport_pro_low']} to ${PRICING['matterport_pro_high']}, custom-quoted."),
            ("Does the tour need a separate appointment?", "No. It is captured during the same session as the HDR stills."),
            (f"Can I add a floor plan for a {n} listing?", f"Yes, a 2D floor plan is ${PRICING['floorplan']}."),
        ],
    }


def page_twilight(city):
    n = city["name"]
    body = f"""  <h2>Real twilight, not a virtual sky</h2>
  <p>Virtual twilight has gotten good enough to fool a quick scroll. An editor takes a two o'clock exterior, swaps in a purple sky, and turns the windows on digitally. It costs almost nothing and it looks almost right, which is exactly the problem: the light on the house still comes from overhead at midday, the windows glow without anything lighting the room behind them, and the shadows point the wrong way.</p>
  <p>Real twilight is a second visit at blue hour with the house lit. The light is genuinely coming from where it appears to come from, so the frame holds up at full screen on a tablet at nine at night &mdash; which is exactly when and how buyers are looking. For the side-by-side, see <a href="twilight.html">the real twilight page</a>.</p>

  <h2>Why blue hour works on {n} listings</h2>
  <p>{city['positioning']}</p>
  <p>In this market twilight earns its keep by making {city['twilight']}.</p>

{pricing_strip(f"Twilight pricing for {n} listings", f"Real twilight is a ${PRICING['twilight_addon']} add-on to the Essential tier and is included free in Showcase (${PRICING['showcase']}) and Signature (${PRICING['signature']}). It pairs with a 3D virtual tour (${PRICING['tour_addon']} add-on) on listings where the gallery is doing the showing.")}

  <h2>Scheduling the blue-hour window in West Michigan</h2>
  <p>Blue hour is short and it moves all year. In West Michigan the usable window runs roughly twenty to forty minutes after sunset, which in late June means shooting close to ten at night and in December means being set up before five in the afternoon. That is the practical scheduling note for a {n} listing: in summer the twilight visit is late, in winter it is early, and in both cases it is a narrow window that has to be booked rather than squeezed in.</p>
  <p>Because the window is short, the house needs to be ready before it opens: interior lights on throughout, landscape and porch lighting on, garage lit, blinds set, and cars moved. A twilight frame is largely made in the fifteen minutes of preparation before the light arrives.</p>

  <h2>Which {n} listings we shoot at twilight</h2>
  <ul>
{bullets([f"<strong>{b[0].upper() + b[1:]}</strong>" for b in city['neighborhoods']])}
  </ul>

{booking_block(city, f"{n} is {city['travel_note']}. ")}

  <h2>{n} twilight photography FAQ</h2>
{faq_html([
    (f"How much does real twilight cost in {n}?", f"${PRICING['twilight_addon']} as an add-on to the Essential tier (${PRICING['essential']}), and included free in Showcase (${PRICING['showcase']}) and Signature (${PRICING['signature']})."),
    ("Is this a real shoot or an edited sky?", "A real shoot. It is a separate visit at blue hour with the house lit, not a daytime exterior with a sky replaced in post."),
    (f"When would you shoot a {n} listing at twilight?", "Roughly twenty to forty minutes after sunset, which shifts across the year &mdash; close to ten at night in late June, before five in the afternoon in December."),
    ("What does the seller need to do?", "Turn on every interior light, the porch and landscape lighting, and the garage; set the blinds; and move the cars. The frame is largely made in that preparation."),
])}"""
    return {
        "title": f"Real Twilight Real Estate Photography {n}, MI | Elzinga Creative Studio",
        "desc": f"Real blue-hour twilight photography for {n}, MI listings &mdash; a genuine second visit, not a virtual sky swap. ${PRICING['twilight_addon']} add-on, free in Showcase and Signature."[:158],
        "eyebrow": f"{city['eyebrow']} &middot; Real Twilight",
        "h1": f"Real twilight photography in <em>{n}</em>.",
        "sub": f"A genuine blue-hour visit with the house lit, not a sky swapped in post. ${PRICING['twilight_addon']} added to Essential for {n} listings, and included free in Showcase and Signature.",
        "body": body,
        "gallery_label": f"Recent Work, {n}",
        "gallery_title": "The gallery twilight is the closing frame of.",
        "gallery_sub": f"Twilight is one frame in a {n} listing, not the whole set. It works because the rest of the gallery is clean: verticals true, windows balanced, sky real, nothing in the frame that should not be there.",
        "cta": f"Listing in {n}? Let's shoot the blue hour.",
        "faqs": [
            (f"How much does real twilight cost in {n}?", f"${PRICING['twilight_addon']} as an add-on to Essential (${PRICING['essential']}), and included free in Showcase (${PRICING['showcase']}) and Signature (${PRICING['signature']})."),
            ("Is this a real shoot or an edited sky?", "A real shoot &mdash; a separate visit at blue hour with the house lit, not a daytime exterior with a replaced sky."),
            (f"When is twilight shot on a {n} listing?", "Roughly twenty to forty minutes after sunset, which moves across the year from close to ten at night in late June to before five in the afternoon in December."),
            ("What does the seller need to do beforehand?", "Interior lights on throughout, porch and landscape lighting on, garage lit, blinds set, cars moved."),
        ],
    }


COMPOSERS = {"drone": page_drone, "video": page_video, "tour": page_tour, "twilight": page_twilight}


# ------------------------------------------------------------------- rendering

def render(shell, service_key, city_slug):
    city = dict(CITIES[city_slug], slug=city_slug)
    svc = SERVICES[service_key]
    p = COMPOSERS[service_key](city)
    url = url_for(service_key, city_slug)
    canon = BASE + url
    og_img = BASE + f"images/web/{city['imgs'][0]}-1600.jpg"
    plain_desc = re.sub(r"&mdash;", "-", p["desc"])

    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Service",
                "@id": canon + "#service",
                "name": f"{svc['label']} {city['name']} Michigan",
                "image": og_img,
                "description": plain_desc,
                "provider": {"@id": BASE + "#business"},
                "areaServed": {"@type": "City", "name": city["name"], "containedInPlace": {"@type": "State", "name": "Michigan"}},
                "offers": [{"@type": "Offer", "name": svc["label"], "price": str(svc["price"]), "priceCurrency": "USD"}],
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE},
                    {"@type": "ListItem", "position": 2, "name": svc["label"], "item": BASE + svc["hub"]},
                    {"@type": "ListItem", "position": 3, "name": city["name"], "item": canon},
                ],
            },
            {
                "@type": "FAQPage",
                "mainEntity": [
                    {"@type": "Question", "name": re.sub(r"&mdash;", "-", q),
                     "acceptedAnswer": {"@type": "Answer", "text": re.sub(r"<[^>]+>", "", a).replace("&mdash;", "-")}}
                    for q, a in p["faqs"]
                ],
            },
        ],
    }

    return f"""<!DOCTYPE html>
<html lang="en">
{GENERATED}
<head>
{shell['gtm_head']}
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{p['title']}</title>
  <meta name="description" content="{html.escape(plain_desc, quote=True)}" />
  <link rel="canonical" href="{canon}" />

  <meta property="og:type" content="website" />
  <meta property="og:url" content="{canon}" />
  <meta property="og:title" content="{html.escape(p['title'], quote=True)}" />
  <meta property="og:description" content="{html.escape(plain_desc, quote=True)}" />
  <meta property="og:image" content="{og_img}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="800" />
  <meta property="og:locale" content="en_US" />
  <meta property="og:site_name" content="Elzinga Creative Studio" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image" content="{og_img}" />
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
  <script type="application/ld+json">
{json.dumps(schema, indent=2)}
  </script>

{shell['fonts']}
{shell['css']}
{shell['style']}
</head>
<body>
{shell['gtm_body']}

{shell['header']}

<section id="hero">
  <div class="hero-inner">
    <p class="breadcrumb"><a href="index.html">Home</a> &nbsp;/&nbsp; <a href="{svc['hub']}">{svc['label']}</a> &nbsp;/&nbsp; {city['name']}</p>
    <p class="hero-eyebrow">{p['eyebrow']}</p>
    <h1 class="hero-h1">{p['h1']}</h1>
    <p class="hero-sub">{p['sub']}</p>
    <a href="preferred-photographer.html" class="hero-cta">See Pricing</a>
  </div>
</section>

<article class="reveal">
{p['body']}
</article>

<section class="work-gallery reveal">
  <span class="work-gallery-label">{p['gallery_label']}</span>
  <h2 class="work-gallery-title">{p['gallery_title']}</h2>
  <p class="work-gallery-sub">{p['gallery_sub']}</p>
  <div class="work-grid">
{gallery(city)}
  </div>
</section>

{nearby_block(service_key, city_slug, city)}

<section id="cta-band">
  <h2 class="cta-title">{p['cta']}</h2>
  <a href="preferred-photographer.html" class="btn-white">See Realtor Pricing</a>
  <a href="realtors.html#start" class="btn-white" style="margin-left:12px;">Book this listing &rarr;</a>
</section>

{footer(city)}

{shell['footer_scripts']}
"""


# ----------------------------------------------------------- crawl-path inject

def crosslink_block(city_slug):
    city = CITIES[city_slug]
    rows = "\n".join(
        f'    <li><a href="{url_for(k, city_slug)}"><strong>{SERVICES[k]["nav_label"]} in {city["name"]}</strong>, {SERVICES[k]["price_line"]}</a></li>'
        for k in SERVICE_ORDER
    )
    return f"""{CROSSLINK_START}
<section class="nearby-areas reveal">
  <div class="nearby-inner">
    <span class="nearby-label">More in {city['name']}</span>
    <h2 class="nearby-title">Everything else we shoot in <em>{city['name']}.</em></h2>
    <ul class="nearby-list">
{rows}
    </ul>
  </div>
</section>
{CROSSLINK_END}"""


def inject_crosslinks(dry_run=False):
    """Add (or refresh) the matrix link block on each city photography page."""
    touched = []
    for slug in CITY_ORDER:
        path = os.path.join(ROOT, f"real-estate-photography-{slug}.html")
        if not os.path.exists(path):
            print(f"  ! no photography page for {slug}, skipping crosslink")
            continue
        src = open(path, encoding="utf-8").read()
        block = crosslink_block(slug)
        if CROSSLINK_START in src:
            new = re.sub(re.escape(CROSSLINK_START) + r".*?" + re.escape(CROSSLINK_END), lambda _: block, src, flags=re.S)
        else:
            # The cta-band section carries varying attributes across pages, and a
            # couple of pages have none at all — fall back to the footer.
            m = re.search(r'<section id="cta-band"[^>]*>', src) or re.search(r"<footer[^>]*>", src)
            if not m:
                print(f"  ! no cta-band or footer anchor in {slug}, skipping crosslink")
                continue
            new = src[: m.start()] + block + "\n\n" + src[m.start():]
        if new != src:
            touched.append(slug)
            if not dry_run:
                open(path, "w", encoding="utf-8").write(new)
    return touched


# ------------------------------------------------------------------- sitemap

def update_sitemap(urls, dry_run=False):
    path = os.path.join(ROOT, "sitemap.xml")
    src = open(path, encoding="utf-8").read()
    today = date.today().isoformat()
    existing = set(re.findall(r"<loc>(.*?)</loc>", src))
    entries = []
    for u in urls:
        full = BASE + u
        if full in existing:
            continue
        entries.append(
            f"  <url>\n    <loc>{full}</loc>\n    <lastmod>{today}</lastmod>\n"
            f"    <changefreq>monthly</changefreq>\n    <priority>0.7</priority>\n  </url>"
        )
    if not entries:
        return 0
    new = src.replace("</urlset>", "\n".join(entries) + "\n</urlset>")
    if not dry_run:
        open(path, "w", encoding="utf-8").write(new)
    return len(entries)


# ----------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--check", action="store_true", help="fail if any page is out of date")
    args = ap.parse_args()

    shell = load_shell()
    written, unchanged, stale, refused = [], [], [], []

    for city_slug in CITY_ORDER:
        for service_key in SERVICE_ORDER:
            url = url_for(service_key, city_slug)
            path = os.path.join(ROOT, url)
            out = render(shell, service_key, city_slug)
            if os.path.exists(path):
                cur = open(path, encoding="utf-8").read()
                if GENERATED not in cur:
                    refused.append(url)
                    continue
                if cur == out:
                    unchanged.append(url)
                    continue
                stale.append(url)
            if args.check:
                continue
            if not args.dry_run:
                open(path, "w", encoding="utf-8").write(out)
            written.append(url)

    all_urls = [url_for(s, c) for c in CITY_ORDER for s in SERVICE_ORDER]

    if args.check:
        print(f"check: {len(unchanged)} current, {len(stale)} stale, {len(refused)} hand-edited")
        for u in stale:
            print("  STALE:", u)
        for u in refused:
            print("  HAND-EDITED (not overwritten):", u)
        return 1 if stale else 0

    added = update_sitemap(all_urls, dry_run=args.dry_run)
    linked = inject_crosslinks(dry_run=args.dry_run)

    print(f"matrix: {len(CITY_ORDER)} cities x {len(SERVICE_ORDER)} services = {len(all_urls)} pages")
    print(f"  written/updated : {len(written)}")
    print(f"  unchanged       : {len(unchanged)}")
    print(f"  refused (hand-edited): {len(refused)}")
    print(f"  sitemap entries added : {added}")
    print(f"  city pages cross-linked: {len(linked)}")
    if args.dry_run:
        print("  (dry run — nothing written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
