"""
ECS programmatic local-SEO matrix — data layer.

One entry per city, one entry per service. `build_matrix.py` renders
{service} x {city} pages from this file. Edit here, never edit a generated page.

GUARDRAILS (every generated page must hold to these — they are the reason the
pages are safe to publish unattended):

  * Every price here is the LIVE published price. If a price changes on
    preferred-photographer.html / twilight.html / matterport-3d-tour-grand-rapids.html /
    real-estate-video-walkthrough-grand-rapids.html, change it HERE too and rebuild.
  * Airspace text is a real, checkable fact per city (FAA class + whether LAANC
    applies). Never invent one. If a city's airspace is unknown, say what we do
    (pre-shoot check + file where required), not what class it is.
  * No review counts, no star ratings, no "best in West Michigan", no founding year.
  * Phone is Kaden's real line only: (616) 258-4578.
  * Claims that must stay true: Part 107 RPIC on every flight; next-business-day
    delivery; travel free within ~25 miles of downtown Grand Rapids (Muskegon and
    the far lakeshore are outside it and are stated as such).
"""

# ---------------------------------------------------------------- shared facts

PRICING = {
    "essential": 245,
    "showcase": 375,
    "signature": 525,
    "drone_addon": 125,
    "twilight_addon": 150,
    "tour_addon": 100,
    "floorplan": 75,
    "reel_single": 150,
    "reel_package": 300,
    "matterport_pro_low": 250,
    "matterport_pro_high": 295,
    "referral_credit": 50,
}

PHONE = "(616) 258-4578"
PHONE_TEL = "+16162584578"

# ---------------------------------------------------------------------- cities
# airspace.class  : plain-language FAA class for the bulk of the city
# airspace.laanc  : "required" | "partial" | "rare"  (drives the copy + the FAQ)
# airspace.text   : the sentence that goes on the page. Must be true.
# aerial          : what an aerial actually PROVES in this market (the drone page's spine)
# reel            : what a listing video has to carry here (the video page's spine)
# tour            : who the 3D walkthrough is really for here (the tour page's spine)
# twilight        : why blue hour earns its keep here (the twilight page's spine)

CITIES = {
    "wyoming": {
        "name": "Wyoming",
        "eyebrow": "Wyoming, MI",
        "county": "Kent County",
        "positioning": "Wyoming is one of West Michigan's largest cities and the established southwest suburb of Grand Rapids. The housing stock is affordable and settled, which makes it a high-velocity entry-level and move-up market: first-time buyers and growing families trading up without leaving the area.",
        "sells_on": "value and speed",
        "neighborhoods": [
            "established starter homes near Metro Health Village",
            "move-up homes in the Wyoming Public Schools, Godwin Heights, and Kelloggsville districts",
            "properties near the 44th Street and Wilson retail corridors",
            "homes along the Buck Creek and Byron Center Avenue corridors",
            "investor and flip listings that need a fast, clean turnaround",
        ],
        "schools": "Wyoming Public Schools, with parts of the city in the Godwin Heights and Kelloggsville districts",
        "airspace": {
            "class": "Class C",
            "laanc": "required",
            "text": "Wyoming is harder airspace than the outer suburbs. The city sits directly next to Gerald R. Ford International Airport (KGRR), which carries Class C controlled airspace, so much of Wyoming falls inside the FAA LAANC grid where a commercial drone flight needs authorization before takeoff. Close to the airport the approved ceilings are lower, and a few pockets need a manual authorization that has to be requested well ahead of the shoot.",
        },
        "aerial": "how a tight established lot actually sits on its street, and how close the home really is to Metro Health Village, US-131, and the retail corridors buyers commute through",
        "reel": "speed. Wyoming moves fast and the buyer pool is broad, so a vertical cut that shows the whole home in thirty seconds does more work here than a slow cinematic piece",
        "tour": "out-of-area and investor buyers who are comparing several affordable listings at once and want to walk the layout before they book a showing",
        "twilight": "an everyday home look like the one buyers picture coming home to, which is exactly the emotional lever in an entry-level and move-up market",
        "nearby": ["grandville", "kentwood", "byron-center", "walker", "grand-rapids"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "kentwood": {
        "name": "Kentwood",
        "eyebrow": "Kentwood, MI",
        "county": "Kent County",
        "positioning": "Kentwood is the southeast Grand Rapids suburb people pick for value and access. It is one of the most diverse communities in West Michigan, sits on the Woodland Mall and the 28th Street and East Paris retail corridor, and moves fast — well-priced homes here do not sit.",
        "sells_on": "value and livability",
        "neighborhoods": [
            "established ranches and split-levels, the bread and butter of Kentwood",
            "condos and townhomes that read best on a mobile MLS scroll",
            "family homes in the Kentwood Public Schools zone",
            "rentals and investment properties in a tight market",
            "homes near Woodland Mall and the 28th Street / East Paris corridor",
        ],
        "schools": "Kentwood Public Schools",
        "airspace": {
            "class": "Class C",
            "laanc": "required",
            "text": "Most of Kentwood sits under Gerald R. Ford International Airport (KGRR) Class C controlled airspace, because the city wraps around the airport. Commercial drone flights here almost always require LAANC authorization before takeoff — it is not optional, and a pilot without it should not be flying your listing.",
        },
        "aerial": "the convenience that is Kentwood's whole pitch: minutes from Woodland Mall, the 28th Street corridor, and the highway, shown in one frame instead of claimed in the remarks",
        "reel": "pace. This is a fast-turning market with a broad buyer pool, so the reel has to hook in the first second and cover the full home before the scroll",
        "tour": "relocating buyers and investors — Kentwood draws both, and a walkthrough link answers the layout question without a second showing",
        "twilight": "a well-priced home stand apart from the identical-looking listing two streets over, which is the whole problem in a market of similar ranches and split-levels",
        "nearby": ["grand-rapids", "cascade", "wyoming", "caledonia", "east-grand-rapids"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "grandville": {
        "name": "Grandville",
        "eyebrow": "Grandville, MI",
        "county": "Kent County",
        "positioning": "Grandville is the established southwest suburb buyers pick when they want a settled, family-focused community with everyday convenience built in. RiverTown Crossings anchors the area as a regional retail hub and I-196 puts downtown Grand Rapids minutes away.",
        "sells_on": "the settled-family lifestyle",
        "neighborhoods": [
            "established family neighborhoods off Wilson Avenue and Chicago Drive",
            "Grandville Public Schools zone homes",
            "Buck Creek-adjacent properties with green space and trail access",
            "homes near RiverTown Crossings and the retail corridor",
            "newer construction toward the southern edge",
        ],
        "schools": "Grandville Public Schools",
        "airspace": {
            "class": "controlled airspace",
            "laanc": "partial",
            "text": "Grandville sits near Gerald R. Ford International Airport (KGRR), so parts of the city fall inside the FAA LAANC grid. That is not a blocker — it means authorization has to be filed before the flight where the grid requires it, and the ceiling confirmed for the specific address.",
        },
        "aerial": "the wooded Buck Creek buffer, the trail access, and how a lot sits relative to schools and parks — the three things Grandville buyers are actually paying a premium for",
        "reel": "the neighborhood, not just the house. Grandville buyers are choosing a settled community, so the cut has to leave the front door and show the street",
        "tour": "move-up families comparing two or three homes in the same district and trying to decide which floor plan actually works for them",
        "twilight": "the family-home feeling that Grandville sells on — porch lights on, backyard glowing, the version of the house buyers imagine living in",
        "nearby": ["wyoming", "jenison", "hudsonville", "byron-center", "walker"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "walker": {
        "name": "Walker",
        "eyebrow": "Walker, MI",
        "county": "Kent County",
        "positioning": "Walker is the suburb buyers choose when they want fast access to downtown Grand Rapids without paying a downtown price. It sits northwest of the city, minutes off I-96 and US-131, with a quick run west to GVSU and Allendale.",
        "sells_on": "convenience and value, not prestige",
        "neighborhoods": [
            "Standale ranch and split-level homes on the spacious lots the district is known for",
            "commuter-convenient homes near I-96 and US-131",
            "Kenowa Hills Public Schools zone homes",
            "homes near Millennium Park and its trails, beaches, and Grand River frontage",
            "established Northwest and South Walker neighborhoods",
        ],
        "schools": "Kenowa Hills Public Schools, with parts of the city in the Comstock Park, Grand Rapids, and Grandville districts",
        "airspace": {
            "class": "controlled airspace shelf",
            "laanc": "partial",
            "text": "Walker sits under the Gerald R. Ford International Airport airspace shelf, so part of the city is controlled airspace that requires LAANC authorization before any flight. Areas of Walker outside the shelf fly under standard Part 107 rules with no authorization needed, so the address gets checked before the shoot rather than on the driveway.",
        },
        "aerial": "how close the home really is to the highway, the schools, and Millennium Park's 1,400 acres — the commute-and-access math a Walker buyer is doing in their head",
        "reel": "the practical case. Walker buyers are commuters and value shoppers, so the cut sells square footage, yard, and how quickly you are on the highway",
        "tour": "buyers moving in from outside the metro who want to understand a split-level layout before they spend a Saturday on it",
        "twilight": "the everyday-value pitch — front porch warm, driveway lit, the 'this is what coming home looks like' frame that a virtual sky swap cannot fake",
        "nearby": ["grand-rapids", "standale", "comstock-park", "grandville", "allendale"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "jenison": {
        "name": "Jenison",
        "eyebrow": "Jenison, MI",
        "county": "Ottawa County",
        "positioning": "Jenison is the suburb families pick when they want a quiet, established community with fast access to both Grand Rapids and the lakeshore. Sitting in Georgetown Township just west of Grandville and Wyoming, it is a true commuter-family market.",
        "sells_on": "school district, family space, and an easy commute",
        "neighborhoods": [
            "Jenison Public Schools zone homes, where the district is the headline",
            "established Georgetown Township neighborhoods off Baldwin, Bauer, and Cottonwood",
            "newer subdivisions on the south and west edges",
            "Grand River and Grand Ravines-adjacent properties",
            "move-up family homes near the Chicago Drive corridor",
        ],
        "schools": "Jenison Public Schools",
        "airspace": {
            "class": "controlled airspace shelf",
            "laanc": "partial",
            "text": "Jenison sits west of Gerald R. Ford International Airport, and parts of the area fall under the controlled-airspace shelf tied to that airport. The UAS grid gets checked for the address and LAANC authorization is filed before the flight whenever a grid cell requires it.",
        },
        "aerial": "ravine views, river proximity, and trail access on the Grand Ravines side of town, plus the school-zone and subdivision context that ground-level photos flatten",
        "reel": "the family walkthrough. Jenison buyers are households picking a district and a daily drive, so the cut moves through the living spaces the way a family would",
        "tour": "out-of-district families narrowing a list before they commit a weekend of showings",
        "twilight": "newer subdivision homes, where blue hour is the difference between a builder-grade exterior and a home with presence",
        "nearby": ["hudsonville", "grandville", "allendale", "wyoming", "zeeland"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "hudsonville": {
        "name": "Hudsonville",
        "eyebrow": "Hudsonville, MI",
        "county": "Ottawa County",
        "positioning": "Hudsonville is the suburb growing families pick when they want newer construction, room to spread out, and a real school district without the Grand Rapids price tag. Old agricultural land has been turning into subdivisions for two decades, and the buyer here is younger and value-driven.",
        "sells_on": "a place to grow into",
        "neighborhoods": [
            "new-construction homes in active subdivisions",
            "family homes in the Hudsonville Public Schools zone",
            "fenced backyards and family spaces",
            "larger lots on the former farmland edges",
            "established homes near downtown Hudsonville and Hughes Park",
        ],
        "schools": "Hudsonville Public Schools",
        "airspace": {
            "class": "Class C",
            "laanc": "required",
            "text": "Most of Hudsonville falls under Gerald R. Ford International Airport's Class C airspace, so a commercial drone flight here requires LAANC authorization before takeoff. The authorization gets pulled for the listing address ahead of time, so the aerials are legal and the agent never has to think about it.",
        },
        "aerial": "lot size, the subdivision layout, and how the home sits in the street grid — on former farmland the land IS the value, and it does not read from the driveway",
        "reel": "new construction. Finishes and flow are what this buyer is comparing, and a moving cut shows a floor plan better than eighteen stills",
        "tour": "families comparing three nearly identical new builds. The walkthrough is how one of them stops being identical",
        "twilight": "a brand-new facade that looks like every other brand-new facade in daylight. Blue hour is the cheapest way to make one build the memorable one",
        "nearby": ["jenison", "zeeland", "grandville", "allendale", "byron-center"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "byron-center": {
        "name": "Byron Center",
        "eyebrow": "Byron Center, MI",
        "county": "Kent County",
        "positioning": "Byron Center is one of the fastest-growing communities on the southwest side of Grand Rapids. Buyers here are largely families chasing newer construction, more square footage per dollar, and the school district, with quick M-6 South Beltline access.",
        "sells_on": "new build value and land",
        "neighborhoods": [
            "new construction and model homes",
            "subdivision homes near the Byron Center Public Schools campuses",
            "rural-edge acreage and larger lots",
            "homes near the 84th Street and US-131 corridor",
            "established homes closer to the village core",
        ],
        "schools": "Byron Center Public Schools",
        "airspace": {
            "class": "controlled airspace shelf",
            "laanc": "partial",
            "text": "Parts of Byron Center fall under the Gerald R. Ford International Airport (KGRR) controlled airspace shelf. Where that applies, LAANC authorization is filed before the shoot; the rest of the township flies under standard Part 107 rules.",
        },
        "aerial": "acreage, privacy, and how a home sits in a subdivision that is still filling in. In Byron Center the lot is frequently the reason for the price, and only the aerial proves it",
        "reel": "the new-build comparison. When the buyer is choosing between identical-looking builds, motion and finish detail are the tiebreaker",
        "tour": "buyers cross-shopping model homes who want to re-walk a floor plan at 9pm without another appointment",
        "twilight": "rural-edge listings where the sky is the whole backdrop, and new construction that needs warmth its landscaping has not grown into yet",
        "nearby": ["wyoming", "caledonia", "grandville", "hudsonville", "cutlerville"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "caledonia": {
        "name": "Caledonia",
        "eyebrow": "Caledonia, MI",
        "county": "Kent County",
        "positioning": "Caledonia is one of the fastest-growing, most affluent markets southeast of Grand Rapids. The buyer is specific: move-up and family buyers trading into more house, more land, and a sought-after school district, an easy M-6 hop from the city.",
        "sells_on": "schools, new construction, and land",
        "neighborhoods": [
            "new-construction subdivisions",
            "acreage and larger lots",
            "Caledonia Community Schools zone homes",
            "move-up family homes with finished basements and backyard family space",
            "homes along the M-6 corridor toward Middleville and Gun Lake",
        ],
        "schools": "Caledonia Community Schools",
        "airspace": {
            "class": "controlled airspace",
            "laanc": "partial",
            "text": "Caledonia sits roughly eight miles southeast of Gerald R. Ford International Airport (KGRR), so parts of the area fall inside the FAA LAANC grid. Authorization is filed before the flight where the grid requires it, and the ceiling is confirmed for the specific address first.",
        },
        "aerial": "true lot size, setback, and the privacy buyers are paying for. On Caledonia acreage the aerial is not a bonus frame, it is the frame that justifies the number",
        "reel": "space. Acreage and new construction both photograph as 'big' from the air and 'nice' from the ground; video is what connects the two",
        "tour": "move-up families comparing large floor plans, and out-of-town buyers relocating into the district",
        "twilight": "higher-band listings where the presentation is expected to match the price, and acreage homes with an open western sky",
        "nearby": ["kentwood", "cascade", "byron-center", "middleville", "alto"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "rockford": {
        "name": "Rockford",
        "eyebrow": "Rockford, MI",
        "county": "Kent County",
        "positioning": "Rockford is the family-focused, downtown-walkable market north of Grand Rapids, built around the Rogue River, a real downtown, and a school district families move for.",
        "sells_on": "walkable downtown and the river",
        "neighborhoods": [
            "homes near downtown Rockford and the Rogue River dam",
            "Rockford Public Schools zone family homes",
            "White Pine Trail-adjacent properties",
            "wooded and larger-lot homes north toward the Cedar Springs corridor",
            "newer construction on the outer edges",
        ],
        "schools": "Rockford Public Schools",
        "airspace": {
            "class": "Class G",
            "laanc": "rare",
            "text": "Rockford sits in Class G uncontrolled airspace for most of the city, the friendliest tier for commercial drone work. No LAANC authorization is needed in most cases. Specific exception zones toward the Cedar Springs area get a pre-shoot check.",
        },
        "aerial": "the river, the trail, and the walk to downtown — the three reasons a buyer pays Rockford prices, none of which a front-elevation photo can show",
        "reel": "the town. Rockford sells its downtown as hard as it sells its houses, so the cut earns its keep by leaving the property",
        "tour": "buyers relocating into the district from outside West Michigan, who cannot easily get to a Saturday showing",
        "twilight": "riverfront and wooded lots, where the light through the trees at blue hour is the single most flattering condition the property will ever be in",
        "nearby": ["comstock-park", "belmont", "cedar-springs", "grand-rapids", "sparta"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "ada": {
        "name": "Ada",
        "eyebrow": "Ada, MI",
        "county": "Kent County",
        "positioning": "Ada is the larger-lot, modern-architecture market east of Grand Rapids, threaded by the Thornapple River and anchored by a rebuilt village core. Buyers searching Ada are explicitly looking for lot size, neighborhood density, and how a home sits relative to the woods, the river, or the street.",
        "sells_on": "land, architecture, and setting",
        "neighborhoods": [
            "Ada Village core homes, a historic and contemporary mix",
            "Bradford and Cascade-adjacent estates",
            "Thornapple River properties",
            "newer subdivisions east of Pettis Avenue",
            "forested-lot homes north of Ada Drive",
        ],
        "schools": "Forest Hills Public Schools",
        "airspace": {
            "class": "Class E corridors",
            "laanc": "partial",
            "text": "Ada sits outside Gerald R. Ford International Airport's Class C core but inside several Class E corridors. Every address gets an airspace check before the shoot and LAANC authorization is filed where a grid cell requires it.",
        },
        "aerial": "lot size, tree cover, river frontage, and property-line context. In Ada the aerial is the difference between a listing that reads as a house and one that reads as a piece of land",
        "reel": "architecture. Modern homes here are designed around sightlines and light, and a moving camera is the only way to show a sightline",
        "tour": "the out-of-town executive buyer relocating into the Forest Hills district who is shortlisting from another state",
        "twilight": "contemporary architecture built for evening light — glass, overhangs, and landscape lighting that only exist at blue hour",
        "nearby": ["cascade", "forest-hills", "east-grand-rapids", "lowell", "grand-rapids"],
        "travel_note": "inside the free travel radius",
        "imgs": ["_DSC8548-HDR", "DSC08891-HDR", "DSC08483-HDR", "DSC08468-HDR"],
    },
    "cascade": {
        "name": "Cascade",
        "eyebrow": "Cascade, MI",
        "county": "Kent County",
        "positioning": "Cascade Township is one of the most affluent suburbs southeast of Grand Rapids, about ten to twelve miles from downtown. The Thornapple River winds past a stretch of riverfront and wooded executive lots, and the township is anchored by top-rated Forest Hills Public Schools.",
        "sells_on": "a premium presentation buyers expect at this price point",
        "neighborhoods": [
            "executive and luxury homes near the Thornapple River",
            "riverfront and wooded estate lots",
            "newer luxury subdivisions",
            "Forest Hills Public Schools zone homes",
            "homes near Cascade Road and the village",
        ],
        "schools": "Forest Hills Public Schools",
        "airspace": {
            "class": "Class C or D",
            "laanc": "required",
            "text": "Cascade has an airspace detail most photographers miss: Gerald R. Ford International Airport (GRR) sits inside Cascade Township, so much of Cascade falls in controlled airspace where a drone flight requires LAANC authorization. That gets pulled ahead of the shoot rather than discovered on site.",
        },
        "aerial": "river frontage, mature tree cover, lot lines, and how a house sits on a large parcel — the specifics that separate two seven-figure listings on the same road",
        "reel": "scale. An executive home is a sequence of spaces, and stills break that sequence into unrelated rooms",
        "tour": "relocating executives and second-home buyers who will not see the property in person until they are already serious",
        "twilight": "the price band. At this level a daylight-only gallery reads as under-marketed, and real blue hour is the visible signal that the listing was taken seriously",
        "nearby": ["ada", "forest-hills", "east-grand-rapids", "kentwood", "caledonia"],
        "travel_note": "inside the free travel radius",
        "imgs": ["_DSC8528-HDR", "DSC08891-HDR", "DSC08483-HDR", "DSC08876-HDR"],
    },
    "forest-hills": {
        "name": "Forest Hills",
        "eyebrow": "Forest Hills & Cascade Township, MI",
        "county": "Kent County",
        "positioning": "Forest Hills is West Michigan's premium suburb market — Cascade Hills Country Club, Egypt Valley, the Forest Hills school district, and estate-scale homes along Cascade Road and Burton. Buyers in this band are deciding which three listings to show in person this weekend.",
        "sells_on": "earning the showing",
        "neighborhoods": [
            "homes proximate to Cascade Hills Country Club",
            "the Egypt Valley Country Club area",
            "Forest Hills school district homes along Pettis, Cascade Road, and Burton",
            "modern architecture and new builds designed for evening light",
            "wooded estate lots with back-of-property compositions",
        ],
        "schools": "Forest Hills Public Schools",
        "airspace": {
            "class": "Class E",
            "laanc": "rare",
            "text": "Forest Hills and most of Cascade Township sit in Class E airspace, friendlier than the Class C controlled airspace around downtown Grand Rapids, and most flights do not require LAANC authorization. Egypt Valley and Cascade Hills both carry additional considerations — course operations and member privacy — handled by pre-shoot coordination rather than improvised on the day.",
        },
        "aerial": "golf course proximity, wooded lot scale, and estate boundaries. At this price band the aerial is what makes a gallery feel like a property tour instead of a house tour",
        "reel": "the narrative. A sixty-second cut is what an agent sends a serious buyer between the gallery and the showing",
        "tour": "the weekend shortlist. A walkthrough link is how a $700K+ listing gets onto a buyer's three-showing Saturday instead of their maybe pile",
        "twilight": "architecture designed for evening lighting. On these homes twilight is not a flourish, it is the condition the architect designed for",
        "nearby": ["cascade", "ada", "east-grand-rapids", "kentwood", "grand-rapids"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08876-HDR", "_DSC8528-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "east-grand-rapids": {
        "name": "East Grand Rapids",
        "eyebrow": "East Grand Rapids, MI",
        "county": "Kent County",
        "positioning": "The East Grand Rapids buyer pool skews higher income and more design-aware than the broader Grand Rapids market. They are scrolling on a tablet at 9pm and they have already seen what real twilight looks like on listings in Ann Arbor, Birmingham, and Holland.",
        "sells_on": "design credibility",
        "neighborhoods": [
            "Reeds Lake waterfront and adjacent homes",
            "historic Gaslight Village and the East GR core",
            "the Forest Hill and Wealthy Street corridor",
            "Manhattan Park and Croswell Forest estate-scale homes",
            "streetscape context, because buyers here choose the neighborhood as much as the home",
        ],
        "schools": "East Grand Rapids Public Schools",
        "airspace": {
            "class": "controlled airspace",
            "laanc": "required",
            "text": "East Grand Rapids sits inside Gerald R. Ford International Airport's controlled airspace, which means commercial drone work requires LAANC authorization on top of Part 107 certification. Every East GR flight is flown with the airspace authorization already in hand.",
        },
        "aerial": "the Reeds Lake premium and the walkability that East GR is priced on — waterfront proximity and the walk to Gaslight Village are both impossible to prove from the sidewalk",
        "reel": "character. Tudor revivals, mid-century brick, and original millwork are detail stories, and detail is what motion holds on",
        "tour": "design-aware buyers who want to understand how an older floor plan actually flows before they spend a Sunday on it",
        "twilight": "credibility with this specific buyer. A virtual-twilight East GR listing reads as trying too hard; a real one reads as 'this is the home'",
        "nearby": ["grand-rapids", "cascade", "forest-hills", "ada", "kentwood"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08881-HDR", "DSC08891-HDR", "DSC08901-HDR", "_DSC8528-HDR"],
    },
    "comstock-park": {
        "name": "Comstock Park",
        "eyebrow": "Comstock Park, MI",
        "county": "Kent County",
        "positioning": "Comstock Park straddles the Grand River about seven miles northwest of downtown Grand Rapids — close enough to be a true commuter community, at a value-to-mid price point that pulls first-time buyers, move-up families, and investors at once.",
        "sells_on": "location and price together",
        "neighborhoods": [
            "Grand River riverfront parcels",
            "established mid-century homes",
            "newer builds and infill construction",
            "value-to-mid homes near the Alpine Avenue corridor",
            "homes near Mill Creek, York Creek, and Dwight Lydell Park",
        ],
        "schools": "Comstock Park Public Schools",
        "airspace": {
            "class": "mixed",
            "laanc": "partial",
            "text": "Comstock Park sits near the edge of the Grand Rapids metro airspace, so unlike the more rural towns to the north, some parcels here fall inside controlled airspace that requires LAANC authorization. Every Comstock Park address gets a pre-shoot airspace check and authorization is pulled ahead of time where it applies.",
        },
        "aerial": "water frontage and the parcel itself. On the Grand River band the river relationship is the premium, and it only reads from the air",
        "reel": "the mix. Comstock Park sells to three different buyers at once, and a video can carry commute, condition, and setting in one pass",
        "tour": "investors and out-of-area buyers screening several value listings without driving to each one",
        "twilight": "riverfront parcels and mid-century homes whose best feature is the setting rather than the finishes",
        "nearby": ["walker", "rockford", "belmont", "grand-rapids", "sparta"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "allendale": {
        "name": "Allendale",
        "eyebrow": "Allendale, MI",
        "county": "Ottawa County",
        "positioning": "Allendale is unusual for West Michigan: one township selling to two completely different buyers at once. Grand Valley State University sits at the center of town along Lake Michigan Drive, driving steady student and investor rental demand, while the township fills in with new family subdivisions.",
        "sells_on": "two markets in one township",
        "neighborhoods": [
            "GVSU rental and investor properties",
            "family subdivision homes",
            "new construction across the growing township",
            "Grand River-adjacent and acreage properties",
            "Allendale Public Schools zone homes",
        ],
        "schools": "Allendale Public Schools",
        "airspace": {
            "class": "Class G",
            "laanc": "rare",
            "text": "Most of Allendale Charter Township sits in Class G uncontrolled airspace, the friendliest tier for commercial drone work, so no LAANC authorization is needed in most cases. Where a controlled-airspace shelf applies to a specific address, authorization is filed before the flight.",
        },
        "aerial": "proximity to campus for the investor buyer and lot size for the family buyer — the same frame answers both of Allendale's markets",
        "reel": "unit clarity for investors and family flow for households. Two different cuts, and it is worth knowing which listing needs which",
        "tour": "out-of-area investor buyers and relocating families alike — the two buyer types Allendale attracts are both frequently shopping from a distance",
        "twilight": "new construction across the township, where blue hour separates a finished home from a build site with sod",
        "nearby": ["jenison", "hudsonville", "walker", "grand-haven", "coopersville"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "holland": {
        "name": "Holland",
        "eyebrow": "Holland, MI",
        "county": "Ottawa County",
        "positioning": "Holland does not sell the way an inland Grand Rapids suburb sells. A real slice of the market is buying water, a second home, or a relocation onto the lakeshore, and many of those buyers are shopping from out of town before they ever stand in the driveway.",
        "sells_on": "the gallery being the showing",
        "neighborhoods": [
            "Lake Macatawa waterfront and channel homes",
            "lakeshore and Holland State Park-adjacent properties",
            "downtown 8th Street walkables",
            "Hope College district homes",
            "West Ottawa, Holland Public, and Holland Christian school zone homes",
        ],
        "schools": "West Ottawa, Holland Public, and Holland Christian",
        "airspace": {
            "class": "Class G",
            "laanc": "rare",
            "text": "The airspace here is friendly: West Michigan Regional Airport, the former Tulip City Airport (BIV), is a non-towered general aviation field, so most of Holland sits in uncontrolled Class G airspace where commercial drone work is straightforward. Where the airport facility map calls for it near BIV, LAANC authorization is filed ahead of the shoot.",
        },
        "aerial": "the frontage, the dock, and the channel run out to Lake Michigan. On Holland waterfront the aerial is not a nice frame, it is the proof the premium is real",
        "reel": "distance. A buyer in Chicago or Indianapolis decides whether to drive four hours based on what they can see, and video carries more of the property than a gallery does",
        "tour": "the out-of-state second-home buyer. Holland's remote buyers are exactly who a walkthrough link was invented for",
        "twilight": "the lakeshore. Sunset over the water is Holland's whole identity, and a listing that does not show it is leaving the town's best asset off the page",
        "nearby": ["zeeland", "saugatuck", "grand-haven", "hudsonville", "douglas"],
        "travel_note": "on the lakeshore, outside the roughly 25-mile free travel radius from downtown Grand Rapids, so a small travel arrangement applies",
        "imgs": ["DSC08478-HDR", "DSC08881-HDR", "DSC08891-HDR", "DSC08483-HDR"],
    },
    "zeeland": {
        "name": "Zeeland",
        "eyebrow": "Zeeland, MI",
        "county": "Ottawa County",
        "positioning": "Zeeland sits next to Holland but has its own gravity, and much of it is employment. MillerKnoll and Gentex both anchor the town, which gives Zeeland something most small towns this size do not have: a steady professional buyer base that does not have to commute far to a good job.",
        "sells_on": "a deliberate, professional buyer",
        "neighborhoods": [
            "established homes near downtown Main Avenue",
            "newer subdivisions on Zeeland's east and north edges",
            "Zeeland Public Schools zone homes",
            "move-up family homes for MillerKnoll and Gentex professionals",
            "affordable starter homes inside the city",
        ],
        "schools": "Zeeland Public Schools",
        "airspace": {
            "class": "mixed",
            "laanc": "partial",
            "text": "Zeeland's location between two airports matters: parts of the city fall under the controlled-airspace shelves of Gerald R. Ford International (GRR) to the east and West Michigan Regional Airport (BIV) in Holland to the southwest. Where those shelves apply, a B4UFLY check and LAANC filing happen before the flight, not on site.",
        },
        "aerial": "lot size and layout in the newer subdivisions on the edges of town, plus the short-commute story that is the whole reason a MillerKnoll or Gentex professional buys here",
        "reel": "the walkable, settled feel near Main Avenue, which is the value a Zeeland buyer is actually paying for and the hardest thing to put in a still",
        "tour": "professionals relocating in for a job who are shopping before they move, and move-up buyers comparing floor plans on the east side",
        "twilight": "newer subdivision homes and move-up listings where the finishes are good and the exterior needs one frame with real presence",
        "nearby": ["holland", "hudsonville", "jenison", "allendale", "grand-haven"],
        "travel_note": "on the lakeshore side, outside the roughly 25-mile free travel radius from downtown Grand Rapids, so a small travel arrangement applies",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
    "grand-haven": {
        "name": "Grand Haven",
        "eyebrow": "Grand Haven, MI",
        "county": "Ottawa County",
        "positioning": "Grand Haven is a lakeshore destination first and a commuter town second. A large slice of the listings are waterfront homes, vacation properties, and second homes bought by buyers from Chicago, Detroit, and across the Midwest who want Lake Michigan access, the State Park beach, and the boardwalk.",
        "sells_on": "a lifestyle and a location",
        "neighborhoods": [
            "Lake Michigan waterfront and dune homes",
            "Grand River channel and boardwalk-adjacent properties",
            "vacation and second homes",
            "downtown homes near Washington Avenue",
            "Grand Haven Area Public Schools zone and Spring Lake-adjacent homes",
        ],
        "schools": "Grand Haven Area Public Schools",
        "airspace": {
            "class": "largely uncontrolled",
            "laanc": "rare",
            "text": "Grand Haven Memorial Airpark is a non-towered general aviation field, so most of the area sits in uncontrolled airspace where commercial drone work is straightforward. Where the FAA facility map calls for authorization near the field or along the channel, LAANC is filed ahead of the shoot and the address is checked first either way.",
        },
        "aerial": "beach proximity, water frontage, the dune setting, and the walk to the boardwalk, the pier, and the lighthouse — every one of them a reason for the price and none of them visible from the front door",
        "reel": "the four-hour drive. Out-of-area buyers often make offers from the marketing alone, and video is the closest thing to standing on the deck",
        "tour": "vacation and second-home buyers shopping from another state, who will not walk the house until they are already committed",
        "twilight": "sunset on the lakeshore. This is the single most saleable thing about a Grand Haven property and the one frame every out-of-town buyer is hoping to see",
        "nearby": ["spring-lake", "muskegon", "holland", "nunica", "allendale"],
        "travel_note": "on the lakeshore, outside the roughly 25-mile free travel radius from downtown Grand Rapids, so a small travel arrangement applies",
        "imgs": ["DSC08478-HDR", "DSC08881-HDR", "DSC08901-HDR", "DSC08891-HDR"],
    },
    "muskegon": {
        "name": "Muskegon",
        "eyebrow": "Muskegon, MI",
        "county": "Muskegon County",
        "positioning": "Muskegon sits about 40 miles west of Grand Rapids, right on Muskegon Lake where it opens to Lake Michigan. It is the largest city on the West Michigan lakeshore and a higher-volume market than the inland bedroom communities, with two clear lanes: value homes in established neighborhoods, and waterfront that commands a premium.",
        "sells_on": "two lanes, two different jobs",
        "neighborhoods": [
            "waterfront listings on Muskegon Lake and the channel",
            "value homes in Lakeside, Glenside, Nims, and Beachwood",
            "Bluffton and Beachwood homes near Pere Marquette Beach",
            "revitalizing downtown and Western Market condos and lofts",
            "higher-end lakeshore properties",
        ],
        "schools": "Muskegon Public Schools and the surrounding lakeshore districts",
        "airspace": {
            "class": "Class D",
            "laanc": "required",
            "text": "Muskegon is different from the inland towns on one important point: Muskegon County Airport (MKG) is towered, so much of the city sits in controlled Class D airspace. Many listings require LAANC authorization before a drone can legally fly, and that gets pulled ahead of the shoot.",
        },
        "aerial": "shoreline, dock, water access, and the home's position relative to the channel and Lake Michigan — the entire basis of the waterfront premium in this market",
        "reel": "volume and contrast. In a high-volume market a moving cut is how a value listing stops looking like the forty others at the same price",
        "tour": "buyers shopping the lakeshore from Grand Rapids, Chicago, and beyond, plus investors screening value stock at scale",
        "twilight": "waterfront and near-water listings, where the sunset over Muskegon Lake is the reason the buyer is looking at Muskegon at all",
        "nearby": ["norton-shores", "grand-haven", "spring-lake", "fruitport", "ravenna"],
        "travel_note": "beyond the roughly 25-mile free travel radius from Grand Rapids, so a small travel arrangement applies",
        "imgs": ["DSC08901-HDR", "DSC08881-HDR", "DSC08478-HDR", "DSC08891-HDR"],
    },
    "saugatuck": {
        "name": "Saugatuck",
        "eyebrow": "Saugatuck &amp; Douglas, MI",
        "county": "Allegan County",
        "positioning": "Saugatuck and its sister village Douglas are an art-town lakeshore market first and everything else second. The two villages sit where the Kalamazoo River meets Lake Michigan, joined by the hand-cranked chain ferry, and the inventory skews to high-end second homes, luxury lakeshore, riverfront condos, and design-forward cottages. The buyer is usually from Chicago or Detroit, purchasing a lifestyle rather than a commute.",
        "sells_on": "a lifestyle bought from four hours away",
        "neighborhoods": [
            "Lake Michigan luxury second homes and dune cottages",
            "Kalamazoo River riverfront condos and homes with dock and boat access",
            "design-forward and architect-built cottages",
            "downtown Butler Street and gallery-district homes",
            "Oval Beach and Mount Baldhead-adjacent properties",
        ],
        "schools": "Saugatuck Public Schools",
        "airspace": {
            "class": "largely uncontrolled",
            "laanc": "rare",
            "text": "Saugatuck and Douglas sit well clear of the towered airports on either side of the lakeshore, so the area is largely uncontrolled airspace where commercial drone work is straightforward. The dune and beach corridor still gets a pre-shoot check, because coastal and park boundaries carry their own restrictions, and authorization is filed anywhere the FAA facility map calls for it.",
        },
        "aerial": "beach proximity, the dune setting, water frontage, and the walk to the ferry and the galleries — the entire basis of a Saugatuck price, and none of it visible from the driveway",
        "reel": "the four-hour drive from Chicago. This buyer decides whether the trip is worth making from the marketing alone, and video is the closest thing to standing on the deck",
        "tour": "the second-home buyer shopping from another state, who will not walk the cottage until they are already serious about it",
        "twilight": "sunset over Lake Michigan, which is the single thing this entire market is priced on and the frame every out-of-town buyer is hoping to find",
        "nearby": ["douglas", "holland", "fennville", "south-haven", "grand-haven"],
        "travel_note": "on the Allegan County lakeshore, well outside the roughly 25-mile free travel radius from downtown Grand Rapids, so a travel arrangement applies",
        "imgs": ["DSC08881-HDR", "DSC08901-HDR", "DSC08891-HDR", "DSC08483-HDR"],
    },
    "lowell": {
        "name": "Lowell",
        "eyebrow": "Lowell, MI",
        "county": "Kent County",
        "positioning": "Lowell is the historic river town on Kent County's east edge — a walkable Main Street, the Flat River meeting the Grand, and acreage that starts almost as soon as the sidewalks end. The buyer is choosing character and land over proximity.",
        "sells_on": "character and acreage",
        "neighborhoods": [
            "historic downtown homes near Main Street and the Riverwalk",
            "Flat River and Grand River lots",
            "rural acreage on Kent County's east edge",
            "new subdivisions in the Lowell Area Schools zone",
            "Fallasburg and covered-bridge-area country homes",
        ],
        "schools": "Lowell Area Schools",
        "airspace": {
            "class": "Class G",
            "laanc": "rare",
            "text": "Lowell sits in Class G uncontrolled airspace roughly 18 miles east of Grand Rapids, the friendliest tier for commercial drone work. Most acreage and river-lot listings need no LAANC authorization at all, which makes drone an easy yes exactly where it matters most out here.",
        },
        "aerial": "lot size, outbuildings, and boundaries. On east-Kent acreage the land is the value, and the land only reads from the air",
        "reel": "the town and the setting. Lowell buyers are buying the Riverwalk, the Showboat, and the countryside as much as the house",
        "tour": "buyers coming from outside the district who want to understand an older, added-onto floor plan before driving out",
        "twilight": "historic homes on Main Street and river lots, where warm windows against a blue sky is the most honest version of a hundred-year-old house",
        "nearby": ["ada", "saranac", "cascade", "alto", "grand-rapids"],
        "travel_note": "inside the free travel radius",
        "imgs": ["DSC08478-HDR", "DSC08483-HDR", "DSC08891-HDR", "DSC08881-HDR"],
    },
}

# -------------------------------------------------------------------- services
# Each service owns its own page shape. They are deliberately NOT the same
# five sections with a word swapped — different H2s, different FAQ, different
# schema offer, different CTA.

SERVICES = {
    "drone": {
        "slug": "drone-real-estate-photography",
        "label": "Drone Real Estate Photography",
        "short": "drone",
        "nav_label": "Drone & aerial",
        "price": PRICING["drone_addon"],
        "price_line": f"${PRICING['drone_addon']} add-on to Essential or Showcase, included in Signature",
        "hub": "blog/drone-laws-grand-rapids-real-estate-agents.html",
        "hub_label": "drone laws for Grand Rapids real estate agents",
    },
    "video": {
        # Slug matches the live Grand Rapids hub (real-estate-video-walkthrough-grand-rapids.html)
        # so the town pages read as children of it.
        "slug": "real-estate-video-walkthrough",
        "label": "Real Estate Video",
        "short": "listing video",
        "nav_label": "Listing video",
        "price": PRICING["reel_single"],
        "price_line": f"${PRICING['reel_single']} for a single-listing vertical reel, ${PRICING['reel_package']} for a multi-listing or branded package",
        "hub": "real-estate-video-walkthrough-grand-rapids.html",
        "hub_label": "the main real estate video page",
    },
    "tour": {
        # Slug matches the live Grand Rapids hub (matterport-3d-tour-grand-rapids.html).
        "slug": "matterport-3d-tour",
        "label": "3D Virtual Tour",
        "short": "3D tour",
        "nav_label": "3D virtual tour",
        "price": PRICING["tour_addon"],
        "price_line": f"${PRICING['tour_addon']} add-on to any photo package",
        "hub": "matterport-3d-tour-grand-rapids.html",
        "hub_label": "the main 3D tour page",
    },
    "twilight": {
        "slug": "twilight-real-estate-photography",
        "label": "Twilight Real Estate Photography",
        "short": "real twilight",
        "nav_label": "Real twilight",
        "price": PRICING["twilight_addon"],
        "price_line": f"${PRICING['twilight_addon']} add-on to Essential, included free in Showcase and Signature",
        "hub": "twilight.html",
        "hub_label": "the real twilight service page",
    },
}

# Order the matrix renders + links in.
SERVICE_ORDER = ["drone", "video", "tour", "twilight"]
CITY_ORDER = list(CITIES.keys())
